# Generated by Django 3.1.6 on 2023-06-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstuser',
            name='emailid',
            field=models.CharField(max_length=60),
        ),
    ]
