# Generated by Django 3.1.6 on 2023-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230616_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('courseicon', models.CharField(max_length=60)),
            ],
        ),
    ]
